# apiVersion: backstage.io/v1alpha1
# kind: User
# metadata:
#   name: itayara
# spec:
#   profile:
#     displayName: Ibrahim Tayara
#     email: ibrtayyara@hotmail.com
#     picture: https://example.com/staff/jenny-with-party-hat.jpeg
#   memberOf: [central-it]
# ---
# apiVersion: backstage.io/v1alpha1
# kind: Group
# metadata:
#   name: central-it
#   description: The infra business unit
# spec:
#   type: business-unit
#   profile:
#     displayName: Central IT
#     email: it@example.com
#     picture: https://example.com/groups/bu-infrastructure.jpeg
#   parent: ops
#   children: [backstage, other]
#   members: [itayara]
# ---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: bobitjkk9-terraform-azure-infra
  description: Stack bobitjkk9
spec:
  owner: cnetral-it
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bobitjkk9-azure-infrastructure-resources
  annotations:
    github.com/project-slug: ibrt2016/terraform-azure-analytics-bobitjkk9 # Change the value to your github repo which contains terraform code.
    backstage.io/techdocs-ref: dir:.
  links:
  - url: https://github.com/claranet/terraform-azurerm-vnet
    title: 'Virtual Network Terraform Module'
    icon: github
  tags:
    - azure
    - vnet
    - terraform
    - high-criticality
    - ticket-number-98998
    - entity-ca
    - owner-bob-tayara
    - stack-bobitjkk9
    - env-prod
    - created-on-2024-07-30
  title: 'Brand New Stack bobitjkk9 - Azure Reource Group and Virtal Network - Ticket #98998' # you can give any title
  description: |
   Create **Azure Virtual Network** in stack **bobitjkk9** and in **prod** environment\
   \
   **Ticket number:**  98998\
   **Created on:**  2024-07-30\
   **Details:**  Create an **Azure Virtual network** and a **resource group** in a brand new stack **bobitjkk9**, in **prod** environment and in **us-east** region\
   **Action:**  Create a new **Resource Group** and a new **Virtual Network**\
   **Brand new stack created?:**  Yes\
   **Azure region:**  us-east\
   **Virtual network address space:**  10.30.0.0/16\
   **Virtual network suffix:**  001\
   **Stack name:**  bobitjkk9\
   **Stack owner:**  bob-tayara\
   **Azure subscription:**  analytics\
   **Criticality:**  High\
   **Entity:**  CA\
   **Cost center:**  00055
spec:
  type: azure-resource
  owner: central-it
  system: bobitjkk9-terraform-azure-infra
  lifecycle: production